ALTER TABLE "customer" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "customer" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "customer_contact" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "customer_contact" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "customer_location" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "customer_location" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section_item" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section_item" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section_milestone" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section_milestone" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "proposal_section" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_permission" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_permission" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role_permission" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role_permission" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role_user" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_role_user" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_settings" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_settings" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_address_information" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_address_information" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_contact_information" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_contact_information" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_proposal_setting" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_proposal_setting" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_theme" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "tenant_theme" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user_contact" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user_contact" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user_location" ALTER COLUMN "created_on_date" SET DATA TYPE timestamp;--> statement-breakpoint
ALTER TABLE "user_location" ALTER COLUMN "modified_on_date" SET DATA TYPE timestamp;