import { definePreset } from '@primevue/themes';
import Aura from '@primevue/themes/aura';

// SwiftCPQ design tokens mirrored into PrimeVue v4's semantic tree.
// The single source of truth is src/styles/tokens.css; this preset wires the
// same values into PrimeVue components so DataTable, Button, InputText, etc.
// pick up the dense workbench look without per-component pt overrides.
//
// Dark theme is primary. Light values are inverted from the same scale.

export const SwiftPreset = definePreset(Aura, {
  semantic: {
    primary: {
      50:  '{amber.50}',
      100: '{amber.100}',
      200: '{amber.200}',
      300: '{amber.300}',
      400: '{amber.400}',
      500: '{amber.500}',
      600: '{amber.600}',
      700: '{amber.700}',
      800: '{amber.800}',
      900: '{amber.900}',
      950: '{amber.950}',
    },
    focusRing: {
      width: '2px',
      style: 'solid',
      color: 'var(--focus-ring)',
      offset: '1px',
    },
    formField: {
      paddingX: '6px',
      paddingY: '0',
      sm: { fontSize: '12px', paddingX: '6px', paddingY: '0' },
      lg: { fontSize: '14px', paddingX: '8px', paddingY: '0' },
      borderRadius: 'var(--r-md)',
      focusRing: { width: '2px', color: 'var(--focus-ring)', offset: '0' },
      transitionDuration: '80ms',
    },
    list: {
      padding: '4px',
      gap: '0',
      header: { padding: '4px 6px' },
      option: { padding: '4px 8px', borderRadius: 'var(--r-sm)' },
      optionGroup: { padding: '4px 8px', fontWeight: '600' },
    },
    content: {
      borderRadius: 'var(--r-md)',
    },
    mask: {
      background: 'rgba(0, 0, 0, 0.55)',
      transitionDuration: '120ms',
    },
    navigation: {
      list: { padding: '4px', gap: '0' },
      item: { padding: '5px 8px', borderRadius: 'var(--r-md)', gap: '6px' },
    },
    overlay: {
      select: { borderRadius: 'var(--r-md)' },
      popover: { borderRadius: 'var(--r-md)', padding: '6px' },
      modal: { borderRadius: 'var(--r-lg)', padding: '16px' },
    },
    colorScheme: {
      dark: {
        primary: {
          color: 'var(--accent)',
          contrastColor: 'var(--accent-fg)',
          hoverColor: 'var(--accent-hover)',
          activeColor: 'var(--accent-hover)',
        },
        highlight: {
          background: 'var(--accent-bg)',
          focusBackground: 'var(--accent-bg)',
          color: 'var(--text-1)',
          focusColor: 'var(--text-1)',
        },
        surface: {
          0:   'var(--surface-0)',
          50:  'var(--surface-50)',
          100: 'var(--surface-100)',
          200: 'var(--surface-200)',
          300: 'var(--surface-300)',
          400: 'var(--surface-400)',
          500: 'var(--surface-500)',
          600: 'oklch(0.55 0.008 250)',
          700: 'oklch(0.62 0.008 250)',
          800: 'oklch(0.78 0.005 250)',
          900: 'oklch(0.88 0.005 250)',
          950: 'oklch(0.96 0.005 250)',
        },
        formField: {
          background: 'var(--surface-100)',
          disabledBackground: 'var(--surface-50)',
          filledBackground: 'var(--surface-100)',
          filledHoverBackground: 'var(--surface-200)',
          filledFocusBackground: 'var(--surface-100)',
          borderColor: 'var(--border)',
          hoverBorderColor: 'var(--border-strong)',
          focusBorderColor: 'var(--accent)',
          invalidBorderColor: 'var(--error)',
          color: 'var(--text-1)',
          disabledColor: 'var(--text-4)',
          placeholderColor: 'var(--text-4)',
          floatLabelColor: 'var(--text-3)',
          floatLabelFocusColor: 'var(--accent)',
          floatLabelActiveColor: 'var(--text-2)',
          floatLabelInvalidColor: 'var(--error)',
          iconColor: 'var(--text-3)',
          shadow: 'none',
        },
        text: {
          color: 'var(--text-1)',
          hoverColor: 'var(--text-1)',
          mutedColor: 'var(--text-3)',
          hoverMutedColor: 'var(--text-2)',
        },
        content: {
          background: 'var(--surface-50)',
          hoverBackground: 'var(--surface-100)',
          borderColor: 'var(--border)',
          color: 'var(--text-1)',
          hoverColor: 'var(--text-1)',
        },
        overlay: {
          select: { background: 'var(--surface-100)', borderColor: 'var(--border)', color: 'var(--text-1)' },
          popover: { background: 'var(--surface-100)', borderColor: 'var(--border)', color: 'var(--text-1)' },
          modal: { background: 'var(--surface-50)', borderColor: 'var(--border)', color: 'var(--text-1)' },
        },
        list: {
          option: {
            focusBackground: 'var(--surface-200)',
            selectedBackground: 'var(--accent-bg)',
            selectedFocusBackground: 'var(--accent-bg)',
            color: 'var(--text-1)',
            focusColor: 'var(--text-1)',
            selectedColor: 'var(--text-1)',
            selectedFocusColor: 'var(--text-1)',
            icon: { color: 'var(--text-3)', focusColor: 'var(--text-1)' },
          },
          optionGroup: { background: 'transparent', color: 'var(--text-3)' },
        },
        navigation: {
          item: {
            focusBackground: 'var(--surface-200)',
            activeBackground: 'var(--surface-200)',
            color: 'var(--text-2)',
            focusColor: 'var(--text-1)',
            activeColor: 'var(--text-1)',
            icon: { color: 'var(--text-3)', focusColor: 'var(--text-1)', activeColor: 'var(--accent)' },
          },
          submenuLabel: { background: 'transparent', color: 'var(--text-3)' },
          submenuIcon: { color: 'var(--text-3)', focusColor: 'var(--text-1)', activeColor: 'var(--accent)' },
        },
      },
      light: {
        primary: {
          color: 'var(--accent)',
          contrastColor: 'var(--accent-fg)',
          hoverColor: 'var(--accent-hover)',
          activeColor: 'var(--accent-hover)',
        },
        highlight: {
          background: 'var(--accent-bg)',
          focusBackground: 'var(--accent-bg)',
          color: 'var(--text-1)',
          focusColor: 'var(--text-1)',
        },
        surface: {
          0:   'var(--surface-0)',
          50:  'var(--surface-50)',
          100: 'var(--surface-100)',
          200: 'var(--surface-200)',
          300: 'var(--surface-300)',
          400: 'var(--surface-400)',
          500: 'var(--surface-500)',
          600: 'oklch(0.55 0.006 250)',
          700: 'oklch(0.45 0.008 250)',
          800: 'oklch(0.32 0.01 250)',
          900: 'oklch(0.22 0.01 250)',
          950: 'oklch(0.16 0.01 250)',
        },
        formField: {
          background: 'var(--surface-0)',
          disabledBackground: 'var(--surface-100)',
          filledBackground: 'var(--surface-50)',
          filledHoverBackground: 'var(--surface-100)',
          filledFocusBackground: 'var(--surface-0)',
          borderColor: 'var(--border)',
          hoverBorderColor: 'var(--border-strong)',
          focusBorderColor: 'var(--accent)',
          invalidBorderColor: 'var(--error)',
          color: 'var(--text-1)',
          disabledColor: 'var(--text-4)',
          placeholderColor: 'var(--text-4)',
          floatLabelColor: 'var(--text-3)',
          floatLabelFocusColor: 'var(--accent)',
          floatLabelActiveColor: 'var(--text-2)',
          floatLabelInvalidColor: 'var(--error)',
          iconColor: 'var(--text-3)',
          shadow: 'none',
        },
        text: {
          color: 'var(--text-1)',
          hoverColor: 'var(--text-1)',
          mutedColor: 'var(--text-3)',
          hoverMutedColor: 'var(--text-2)',
        },
        content: {
          background: 'var(--surface-50)',
          hoverBackground: 'var(--surface-100)',
          borderColor: 'var(--border)',
          color: 'var(--text-1)',
          hoverColor: 'var(--text-1)',
        },
        overlay: {
          select: { background: 'var(--surface-0)', borderColor: 'var(--border)', color: 'var(--text-1)' },
          popover: { background: 'var(--surface-0)', borderColor: 'var(--border)', color: 'var(--text-1)' },
          modal: { background: 'var(--surface-0)', borderColor: 'var(--border)', color: 'var(--text-1)' },
        },
        list: {
          option: {
            focusBackground: 'var(--surface-200)',
            selectedBackground: 'var(--accent-bg)',
            selectedFocusBackground: 'var(--accent-bg)',
            color: 'var(--text-1)',
            focusColor: 'var(--text-1)',
            selectedColor: 'var(--text-1)',
            selectedFocusColor: 'var(--text-1)',
            icon: { color: 'var(--text-3)', focusColor: 'var(--text-1)' },
          },
          optionGroup: { background: 'transparent', color: 'var(--text-3)' },
        },
        navigation: {
          item: {
            focusBackground: 'var(--surface-200)',
            activeBackground: 'var(--surface-200)',
            color: 'var(--text-2)',
            focusColor: 'var(--text-1)',
            activeColor: 'var(--text-1)',
            icon: { color: 'var(--text-3)', focusColor: 'var(--text-1)', activeColor: 'var(--accent)' },
          },
          submenuLabel: { background: 'transparent', color: 'var(--text-3)' },
          submenuIcon: { color: 'var(--text-3)', focusColor: 'var(--text-1)', activeColor: 'var(--accent)' },
        },
      },
    },
  },
});

export default SwiftPreset;
